In [1]:
%matplotlib inline
import warnings
from math import sqrt
warnings.filterwarnings('ignore')
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
import itertools
from math import factorial

### 5.1. Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B. Вычислите, по возможности не используя программирование $
(5E)^{-1}$, где Е – единичная матрица размера 5х5.  
#### Решение:
$$(5E)^{-1}=5^{-1}*E^{-1}$$
Рассуждаем. Матица, обратная единичной матрице - это такая матрица, при умножении на которую единичной матрицы получаеся единичная марица, т.е. $$E^{-1}*E = E$$
Далее, помня свойство $$A*E=A$$ понимаем, что
$$E^{-1}= E$$
Т.е. матрица, обратная единичной, есть единичная матрица.



Таким образом получаем $$(5E)^{-1}=5^{-1}*E^{-1}=0.2*E$$
В нашем случае Е – единичная матрица размера 5х5. Итак получаем:

$0.2*\begin{pmatrix}
1 & 0 & 0 & 0 & 0\\
0 & 1 & 0 & 0 & 0\\
0 & 0 & 1 & 0 & 0\\
0 & 0 & 0 & 1 & 0\\
0 & 0 & 0 & 0 & 1\\
\end{pmatrix} = 
\begin{pmatrix}
0.2 & 0 & 0 & 0 & 0\\
0 & 0.2 & 0 & 0 & 0\\
0 & 0 & 0.2 & 0 & 0\\
0 & 0 & 0 & 0.2 & 0\\
0 & 0 & 0 & 0 & 0.2\\
\end{pmatrix}
$ 


Проверим наши вычисления

In [2]:
np.linalg.inv(5*np.identity(5))

array([[0.2, 0. , 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. , 0. ],
       [0. , 0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0. , 0.2]])

Видим, что расчеты были верными.

### 5.2. Вычислите определитель:

$\begin{vmatrix}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9\\
\end{vmatrix}$
#### Решение:

det = 1*$\begin{vmatrix}
0 & 6\\
8 & 9\\
\end{vmatrix}-
2*\begin{vmatrix}
4 & 6\\
7 & 9\\
\end{vmatrix}+
3*\begin{vmatrix}
4 & 0\\
7 & 8\\
\end{vmatrix}=-48-(2*(-6))+3*32=-48+12+96=60$  
Проерим наши рассчеты

In [3]:
b=np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
np.linalg.det(b)

59.999999999999986

Видим, что мы рассчитали детерминант правильно

### 5.3.1. Вычислите матрицу, обратную данной:
$A=\begin{pmatrix}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9\\
\end{pmatrix}$
#### Решение:

Определим миноры элементов матрицы A

M=$\begin{pmatrix}
-48 & -6 & 32\\
-6 & -12 & -6\\
12 & -6 & -8\\
\end{pmatrix}$

Найдем алгебраические дополнения элементов матрицы A

$A_*=\begin{pmatrix}
-48 & 6 & 32\\
6 & -12 & 6\\
12 & 6 & -8\\
\end{pmatrix}$

Найдет матрицу обратную матрице A

$A^{-1}=A_*^T/detA=
\begin{pmatrix}
-48 & 6 & 12\\
6 & -12 & 6\\
32 & 6 & -8\\
\end{pmatrix}/60=
\begin{pmatrix}
-0.8 & 0.1 & 0.2\\
0.1 & -0.2 & 0.1\\
8/15 & 0.1 & -2/15\\
\end{pmatrix}$   
Проверим праильность вычисления обратной матрицы.

In [4]:
A=np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B=np.array([[-0.8, 0.1, 0.2], [0.1, -0.2, 0.1], [8/15, 0.1, -2/15]])
A.dot(B)

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
       [-8.8817842e-16,  0.0000000e+00,  1.0000000e+00]])

Видим, что мы нашли правильную обраную матрицу матрице A

### 5.3.2. Приведите пример матрицы 4х4, ранг которой равен 1.
#### Решение:


$A=\begin{pmatrix}
1 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0\\
\end{pmatrix}$

Проверим ранг указанной матрицы

In [5]:
A=np.array([[1, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0],])
A

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
np.linalg.matrix_rank(A)

1

Видим, что действительно ранг матрицы A равен 1

### 5.4. Вычислите скалярное произведение двух векторов:  (1, 5)  и  (2, 8)
#### Решение:


Скалярное произведение двух векторов равно 1*2+5*8=42
Проверим

In [7]:
np.array([1, 5]).dot(np.array([2, 8]))

42

Видим, что все правильно

### 5.5 Вычислите смешанное произведение трех векторов: (1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 
#### Решение:


Смешанное произведение векторов a, и и с — это скалярное произведение вектора a на векторное произведение векторов b и c.
Найдем сначало векторное произведение векторов  (1, 5, 0), (2, 8, 7). Оно равно:
$\begin{vmatrix}
i & j & k\\
1 & 5 & 0\\
2 & 8 & 7\\
\end{vmatrix}=i*\begin{vmatrix}
5 & 0\\
8 & 7\\
\end{vmatrix}-
j*\begin{vmatrix}
1 & 0\\
2 & 7\\
\end{vmatrix}+
k*\begin{vmatrix}
1 & 5\\
2 & 8\\
\end{vmatrix}=(35, -7, -2)$
Теперь найдем скалярное произведение полученного вектора на вектор (7, 1.5, 3)

$(35,−7,−2)*(7, 1.5, 3)=245-10.5-6=228.5$  
Проверим


In [8]:
a = np.array([1, 5, 0], float)
b = np.array([2, 8, 7], float)
c = np.array([7, 1.5, 3], float)
v = np.cross(a, b)
print (np.inner(v, c))

228.5


Видим, что свешанное произведение векторов найдено верно